sudo: required

language: java

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: toedter-github
    token:
      secure: "$SONARQUBE_TOKEN"

services:
  - docker

install: true

script:
  - ./gradlew build integrationtest
  - ./gradlew sonarqube
  - docker build -t kaitoedter/ms60min backend/build
  - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - docker push kaitoedter/ms60min
  - docker tag kaitoedter/ms60min registry.heroku.com/microservice-60min/web
  - docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com
  - docker push registry.heroku.com/microservice-60min/web
  - curl -n -X PATCH https://api.heroku.com/apps/microservice-60min/formation -d '{"updates":[{"type":"web","docker_image":"sha256:54b2fcf91c549dfa4da3a3ec268bf896eb0d22bea8899c94c50201cc50052af7"}]}' -H "Content-Type: application/json" -H "Accept: application/vnd.heroku+json; version=3.docker-releases" -H "Authorization: Bearer $HEROKU_AUTH_TOKEN"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
