sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: true

script:
  - ./gradlew build
  - docker build -t kaitoedter/ms60min build
  - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - docker push kaitoedter/ms60min
  - rm ~/.netrc
  - rm ~/.docker/config.json
  - docker login --username=_ --password="$HEROKU_AUTH_TOKEN" registry.heroku.com
  - docker tag kaitoedter/ms60min registry.heroku.com/microservice-60min/web
  - docker push registry.heroku.com/microservice-60min/web

