sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

install: true

script:
  - ./gradlew build
  - docker build -t kaitoedter/ms60min build
  - docker login --email="$DOCKER_EMAIL" --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - docker push kaitoedter/ms60min
